FROM python:3.10-slim
WORKDIR /app
COPY backend /app
RUN pip install --no-cache-dir fastapi[all] sqlalchemy psycopg2-binary uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
