version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timetable
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/timetable
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--",
            "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db-init:
      build:
        context: .
        dockerfile: Dockerfile.backend  # sử dụng chung Dockerfile backend
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/timetable
      volumes:
        - ./backend:/app
      command: ["./wait-for-it.sh", "db:5432", "--", "python", "import_sample_data.py"]

  frontend:
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  db_data:
